#!/usr/bin/env python
import os
import subprocess
import sys

# catversion executable
# Created by Brian Choi - scho602

root = os.path.join(os.getcwd(), 'mount')
filename = sys.argv[1]
version = sys.argv[2]


def cat():
    subprocess.call(["cat", versioned_filename(version)])


def versioned_filename(number):
    return full_path(filename) + ".v" + str(number)


def full_path(partial):
    if partial.startswith("/"):
        partial = partial[1:]
    path = os.path.join(root, partial)
    return path


if __name__ == '__main__':
    cat()
