#!/usr/bin/env python
import os
import sys

root = os.path.join(os.getcwd(), 'mount')


def load_file():
    try:
        filename = sys.argv[1]
        full_filename = full_path(filename)

        count = 0

        for i in range(1,7):
            if os.path.isfile(full_filename + ".v" + str(i)):
                print filename + ".v" + str(i)
                count = count + 1

        if count == 0:
            print 'No versions available for', filename

    except:
        e = sys.exc_info()[0]
        print e
        print 'Likely an invalid number of arguments. Use the following format:'
        print './listversions one.txt'


def full_path(partial):
    if partial.startswith("/"):
        partial = partial[1:]
    path = os.path.join(root, partial)
    return path


if __name__ == '__main__':
    load_file()

