#!/usr/bin/env python
import os
import re
import sys
from shutil import copy

# mkcurrent executable
# Created by Brian Choi - scho602

root = os.path.join(os.getcwd(), 'mount')
filename = sys.argv[1]
version = sys.argv[2]

def load_file():
    try:
        version_pattern = re.compile(r'[1-6]')
        copying_file = versioned_filename(int(version))
        original_file = full_path(filename)

        if not re.match(version_pattern, version):
            print 'Invalid version number. Choose between 1-6'

        elif version == "1":
            print 'Version 1 is already the current version'

        else:
            copy(copying_file, original_file)
            print 'Version', version, 'is now the current version'

    except IOError:
        e = sys.exc_info()[0]
        print 'Version', version, 'does not exist'
    except TypeError:
        e = sys.exc_info()[0]
        print e


def versioned_filename(number):
    return full_path(filename) + ".v" + str(number)


def full_path(partial):
    if partial.startswith("/"):
        partial = partial[1:]
    path = os.path.join(root, partial)
    return path


if __name__ == '__main__':
    load_file()
