#!/usr/bin/env python
import subprocess


# shutdownversions executable
# Created by Brian Choi - scho602


if __name__ == '__main__':
    # Delete the .versiondir directory and all of its content (ie. the files and its versions)
    subprocess.call(["rm", "-r", ".versiondir/"])
    # Unmount the 'mount' directory
    subprocess.call(['fusermount', '-u', 'mount'])

